### ISSUE TITLE
Suggestion on built-in commands

### ISSUE THREAD

**Issue by sayanarijit** [fhill2/xplr.nvim#2]
Here are some thoughts:

With Lua functions, I don't think we need to create built-in commands like `Xplr`. I think we can leave it up to the users what commands they want to define and map to a specific Lua function, or whether they want to do it at all. Binding the Lua functions to some key (not built-in) might be enough. Just like we do with all the LSP functions (hover, action, definition, references etc).

**Comment by sayanarijit** [comment]
This helps us use xplr.nvim together with xplr.vim without a lot of rebinding. This way, we can fall back to xplr.vim when there's some issue with xplr.nvim.

**Comment by fhill2** [comment]
Yes this does makes sense. I went ahead and removed the `default :Xplr` vimL command. :+1:
