### ISSUE TITLE
Unable to run `:lua require("xplr").install({ hide = true })`

### ISSUE THREAD

**Issue by kdheepak** [fhill2/xplr.nvim#3]
I'm getting the following error:

```
E5108: Error executing lua ...vim/site/pack/packer/start/xplr.nvim/lua/xplr/config.lua:1: module 'log1' not found:
        no field package.preload['log1']
        no file './log1.lua'
        no file '/Users/runner/work/neovim/neovim/.deps/usr/share/luajit-2.1.0-beta3/log1.lua'
        no file '/usr/local/share/lua/5.1/log1.lua'
        no file '/usr/local/share/lua/5.1/log1/init.lua'
        no file '/Users/runner/work/neovim/neovim/.deps/usr/share/lua/5.1/log1.lua'
        no file '/Users/runner/work/neovim/neovim/.deps/usr/share/lua/5.1/log1/init.lua'
```

I'm using the latest nightly release of neovim:

```
$ nvim --version | head -1                                                                                                                                         ─╯
NVIM v0.6.0-dev+210-g6751d6254
```

**Comment by kdheepak** [comment]
Is it looking for this file? https://github.com/fhill2/nvim/blob/69ecbee8b9d7206f0146ae2ff4d3920f0e24ec09/lua/log1.lua

It doesn't appear to be used too. I'm guessing it was accidentally committed as part of debugging?

It also is required here: https://github.com/fhill2/xplr.nvim/blob/36214d308ad95ed747baf6557391c85e43d98d97/lua/xplr/utils.lua#L4 but doesn't appear to be used again.

**Comment by fhill2** [comment]
Yes thank you for noticing. Fixed now. 
I was testing some features with a debug file attached and committed by accident. Should really wrap these in a pcall beforehand and or check lazygit better :D

**Comment by kdheepak** [comment]
Great!
