### ISSUE TITLE
Unable to compile msgpack with lua support on macos 

### ISSUE THREAD

**Issue by kdheepak** [fhill2/xplr.nvim#4]
I’m running into various issues trying to compile msgpack from source. Do you know if anyone has tried to install this on a macos?

**Comment by fhill2** [comment]
Untested on OSX atm only linux.

what issues are you having? What is the error when building??

I can't think of any reasons why [libmpack-lua](https://github.com/libmpack/libmpack-lua)  wouldn't build on OS X. 

I could always make an option to have `xplr.nvim` look for the dependencies for the lua client based on the current Luarocks installation. This way `luarocks install nvim-client`  is all that would be needed.

**Comment by kdheepak** [comment]
I’ll post the exact error messages when I’m back at my computer later today. I was getting a linker error saying `-E is not a valid option `. My guess is `libmpack-lua` hasn’t been tested on mac? For one, I believe it expects gcc instead of clang. I tried playing around with the makefile options but couldn’t get it to work. I’ll open detailed issues on that repo when I get the chance.

**Comment by kdheepak** [comment]
I did a fresh install and it worked just using the default install instructions (I don't understand why though). I'll close this issue.
