### ISSUE TITLE
keybindings don't work

### ISSUE THREAD

**Issue by dchinmay2** [fhill2/xplr.nvim#6]
The keybindings for telescope preview, set nvim cwd, open in nvim etc don't work
`:checkhealth xplr` is fine.
xplr version 0.14.7
neovim 0.5.0
xplr.nvim config - [the example config](https://github.com/fhill2/xplr.nvim#configuration)
xplr config - https://git.sr.ht/~p00f/dotfiles/tree/main/item/cli-tools/.config/xplr/init.lua

**Comment by dchinmay2** [comment]
```
      style = "single",
      highlight = "FloatBorder",
```
in setup have no effect either, there is no border

**Comment by fhill2** [comment]
Hi @p00f thank you for finding these issues. I'm going to go ahead and fix the border.

Regarding keybindings,
What is the output of xplr when opening `xplr.nvim`:
:! enter shell
`cat $XPLR_PIPE_LOGS_OUT`

**Comment by p00f** [comment]
do you mean echo instead of cat? Both of them are empty

**Comment by dchinmay2** [comment]
Ah you meant inside the xplr floating window:
`warning key map not found.`

**Comment by fhill2** [comment]
Are you sure the error msg is from the subshell of xplr? It usually shows more info like line info, file etc. Subshell needs to be used as the env variables are only active within the subshell.
https://arijitbasu.in/xplr/en/message.html#environment-variables
beginning of that chapter explains it.

The xplr error behaviour during startup is different to  nvim.
Not all errors are displayed in Xplr if something errors during startup.
If something isn't working inside xplr I create a shell within xplr using `:!` and then running `cat $XPLR_PIPE_LOGS_OUT` you are able to see the output of the xplr lua environment.

Strange, I tested with the 2 configs above and im able to see the xplr mappings defined in your xplr `init.lua` and the defaults applied by `xplr.nvim` in the action menu

By default all `xplr.nvim` keybindings go under the`action` menu, so `:` inside nvim should show them.

**Comment by dchinmay2** [comment]
Ohh they are under `:`. Thanks. I thought this was a special xplr mode with keymaps
